import type { Metadata, Viewport } from 'next';
import { Suspense } from 'react';
import '@/styles/globals.css';
import { MobileDetector, ThemeProvider, ToasterProvider } from '@/components';
import { cn, staticMetadata } from '@/utils';
import localFont from 'next/font/local';

export const metadata: Metadata = staticMetadata({
  title: '일일 업무 보고 생성기',
  description: 'Generated by create next app',
});

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  userScalable: false,
  viewportFit: 'cover',
  // 안드로이드 가상 키보드가 layout viewport를 함께 축소하도록 지정
  // → fixed 위치의 모바일 복사 바가 키보드에 가려지지 않고 자동으로 위로 올라간다
  interactiveWidget: 'resizes-content',
};

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
  preload: false,
});

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="ko">
      <body
        className={cn(
          pretendard.variable,
          'touch-pan-y bg-background font-pretendard break-keep text-foreground antialiased select-none'
        )}
      >
        <Suspense>
          <ThemeProvider>{children}</ThemeProvider>
        </Suspense>

        <ToasterProvider />

        <MobileDetector />

        {/* For Portal Component */}
        <div id="next-app-portal" />
      </body>
    </html>
  );
}
